### ISSUE TITLE
TenosrRt float16 cannot predict correctly.

### ISSUE THREAD

**Issue by QinWinner** [zhangjinsong3/SOLOv2.tensorRT#10]
As my question shows, I cannot get the correct prediction result when using float16. Obtained predictions often do not have any segmentation results. When I converted tensorRt to float32, all the problems were solved.

**Comment by QinWinner** [comment]
I have solved the problem, it was my failure to export the onnx to float16 format that was causing the problem. However, I need to make a small change to the original code to export to float16 onnx format. All the changes are basically in the if ONNX_EXPORT section, so I'll give a small example here.
![image](https://user-images.githubusercontent.com/49186574/147390485-86070625-6556-4bb3-9200-1cea119bfa3c.png)

**Comment by ke-dev** [comment]
Hi developer, how did you convert to tensorrt model, did you use the onnx2trt tool，

much appreciation

**Comment by QinWinner** [comment]
> you can try using the library https://github.com/onnx/onnx-tensorrt

**Comment by QinWinner** [comment]
> 
you can try using the library https://github.com/onnx/onnx-tensorrt

**Comment by QinWinner** [comment]
@ke-dev  you can try using the library https://github.com/onnx/onnx-tensorrt
