### ISSUE TITLE
Torch1. 4 how to communicate with tensorrt7 2.1 simultaneous installation?

### ISSUE THREAD

**Issue by jyq-lab** [zhangjinsong3/SOLOv2.tensorRT#11]
Tensorrt7 2.1 requirement cuda10.2,cudnn8.1，but torch1.4 no cuda10.2.How to use torch1.5 or 1.6 or later to install solov2?

**Comment by ke-dev** [comment]
CUDA=10.2
cudnn=8.0.5
tensorrt==7.2.1.6
pytorch==1.4.0
torchvision==0.5.0
onnx==1.8.0
onnxruntime==1.6.0
onnx-tensorrt==7.2.1
