### ISSUE TITLE
Couldn't export python operator DeformConvFunction

### ISSUE THREAD

**Issue by shijianjian** [zhangjinsong3/SOLOv2.tensorRT#4]
I think I did follow all the steps noted in the deployment docs. Everything goes well apart from parsing the deformconvfunction, any help is appreciated!

The code runs well whilst training, but failed on converting. And I have checked the log whilst ```pip install -v -e .``` which indicated that the DCN has been properly compiled and installed.

```bash
Traceback (most recent call last):
  File "onnx_exporter_solov2.py", line 223, in <module>
    convert2onnx(args, dummy_input)
  File "onnx_exporter_solov2.py", line 99, in convert2onnx
    torch.onnx.export(model, dummy_input, args.out, input_names=input_names, output_names=output_names, verbose=True, opset_version=11)
  File "/home/10t/jian/anaconda3/envs/lane/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/10t/jian/anaconda3/envs/lane/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/10t/jian/anaconda3/envs/lane/lib/python3.7/site-packages/torch/onnx/utils.py", line 706, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: ONNX export failed: Couldn't export Python operator DeformConvFunction
```

**Comment by zhangjinsong3** [comment]
@shijianjian ONNX and TensorRT do not support DeformConv yet! U need create an custom plugin for tensorRT and a register for onnx. I have not tried it yet!

register for onnx should be like bellow:
```
    @staticmethod
    def symbolic(
            g, input, offset, mask, weight, bias, stride, padding, dilation, deformable_groups,
    ):
        from torch.nn.modules.utils import _pair

        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)
        # as of trt 7, the dcn operation will be translated again by modifying the onnx file
        # so the exporting code is kept to resemble the forward()
        return g.op(
            "DCNv2_2",
            input,
            offset,
            mask,
            weight,
            bias,
            stride_i=stride,
            padding_i=padding,
            dilation_i=dilation,
            deformable_groups_i=deformable_groups,
        )
```

**Comment by shijianjian** [comment]
Hi @zhangjinsong3,

Thanks for the response. I have tried to make it work with the following:
```python
    @staticmethod
    def symbolic(
        g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,
    ):
        from torch.nn.modules.utils import _pair

        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)
        # as of trt 7, the dcn operation will be translated again by modifying the onnx file
        # so the exporting code is kept to resemble the forward()
        return g.op(
            "DCNv2_2",
            input,
            offset,
            weight,
            stride_i=stride,
            padding_i=padding,
            dilation_i=dilation,
            groups_i=groups,
            deformable_groups_i=deformable_groups,
        )
```

The whole thing start to compile but I will get the following warning and error:
```bash
Warning: Unsupported operator DCNv2_2. No schema registered for this operator.

RuntimeError: No Op registered for DCNv2_2 with domain_version of 11
```

I am new to ONNX and not sure what is the proper fix. Any ideas?

Thank you in advance.

**Comment by zhangjinsong3** [comment]
@shijianjian the symbolic sample is a diffierent version of DCN. For mmdet version, it should be like 

```
    @staticmethod
    def symbolic(
            g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,im2col_step
    ):
        return g.op(
            "DCNv2_mmdet",
            input,
            offset,
            weight,
            stride_i=stride,
            padding_i=padding,
            dilation_i=dilation,
            groups_i=groups,
            deformable_groups_i=deformable_groups,
            im2col_step_i=im2col_step
        )
```
The symbolic can help u export an onnx model, but it can be successfully run. You still need an plugin for DCNv2 in tensorRT like [dcnv2_trt](https://github.com/eweill-nv/dcnv2_trt). Currently,I don`t run DCNv2 well on tensorRT 7.

**Comment by shijianjian** [comment]
> @shijianjian the symbolic sample is a diffierent version of DCN. For mmdet version, it should be like
> 
> ```
>     @staticmethod
>     def symbolic(
>             g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,im2col_step
>     ):
>         return g.op(
>             "DCNv2_mmdet",
>             input,
>             offset,
>             weight,
>             stride_i=stride,
>             padding_i=padding,
>             dilation_i=dilation,
>             groups_i=groups,
>             deformable_groups_i=deformable_groups,
>             im2col_step_i=im2col_step
>         )
> ```

Adding the additional ```im2col_step``` will result in a wierd error that:
```bash
TypeError: symbolic() missing 1 required positional argument: 'im2col_step' (occurred when translating DeformConvFunction)
```
But if without, it worked.

> The symbolic can help u export an onnx model, but it can be successfully run. You still need an plugin for DCNv2 in tensorRT like [dcnv2_trt](https://github.com/eweill-nv/dcnv2_trt).

Thanks, I will try to go with it.

>Currently,I don`t run DCNv2 well on tensorRT 7.

BTW, if DCNv2 cannot be compiled, then how do I convert SOLOv2 model to tensorrt? Is there any workaround path you went for?

**Comment by zhangjinsong3** [comment]
Set `enable_onnx_checker=False` in fuction `torch.onnx.export`. Have a try.

**Comment by shijianjian** [comment]
> enable_onnx_checker=False

no luck on that. I have to remome the ```im2col_step``` flag to make it work.

**Comment by shijianjian** [comment]
It turns out that there are args missing in the following calls:
https://github.com/zhangjinsong3/SOLOv2.tensorRT/blob/790835b71e49233352fcf76e35456a1d4eb180a9/mmdet/ops/dcn/deform_conv.py#L238-L240

https://github.com/zhangjinsong3/SOLOv2.tensorRT/blob/790835b71e49233352fcf76e35456a1d4eb180a9/mmdet/ops/dcn/deform_conv.py#L278-L281

Need to add a ```self.im2col_step``` to the end. Then the whole symbolic can run successfully.

The proper corresponding DCNv2 plugin shall be [this one](https://github.com/lesliejackson/TensorRT7-DCNv2-Plugin)

**Comment by fweinan** [comment]
> > @shijianjian the symbolic sample is a diffierent version of DCN. For mmdet version, it should be like
> > ```
> >     @staticmethod
> >     def symbolic(
> >             g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,im2col_step
> >     ):
> >         return g.op(
> >             "DCNv2_mmdet",
> >             input,
> >             offset,
> >             weight,
> >             stride_i=stride,
> >             padding_i=padding,
> >             dilation_i=dilation,
> >             groups_i=groups,
> >             deformable_groups_i=deformable_groups,
> >             im2col_step_i=im2col_step
> >         )
> > ```
> 
> Adding the additional `im2col_step` will result in a wierd error that:
> 
> ```shell
> TypeError: symbolic() missing 1 required positional argument: 'im2col_step' (occurred when translating DeformConvFunction)
> ```
> 
> But if without, it worked.
> 
> > The symbolic can help u export an onnx model, but it can be successfully run. You still need an plugin for DCNv2 in tensorRT like [dcnv2_trt](https://github.com/eweill-nv/dcnv2_trt).
> 
> Thanks, I will try to go with it.
> 
> > Currently,I don`t run DCNv2 well on tensorRT 7.
> 
> BTW, if DCNv2 cannot be compiled, then how do I convert SOLOv2 model to tensorrt? Is there any workaround path you went for?

excuse me, after reading these contents, I can not understand where should place the codes

**Comment by fweinan** [comment]
I add the "symbolic" codes in the end of class ModulatedDeformConvFunction(Function)，but result in a wierd error that:

> @shijianjian the symbolic sample is a diffierent version of DCN. For mmdet version, it should be like
> 
> ```
>     @staticmethod
>     def symbolic(
>             g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,im2col_step
>     ):
>         return g.op(
>             "DCNv2_mmdet",
>             input,
>             offset,
>             weight,
>             stride_i=stride,
>             padding_i=padding,
>             dilation_i=dilation,
>             groups_i=groups,
>             deformable_groups_i=deformable_groups,
>             im2col_step_i=im2col_step
>         )
> ```
> 
> The symbolic can help u export an onnx model, but it can be successfully run. You still need an plugin for DCNv2 in tensorRT like [dcnv2_trt](https://github.com/eweill-nv/dcnv2_trt). Currently,I don`t run DCNv2 well on tensorRT 7.

**Comment by fweinan** [comment]
I add the "symbolic" codes in the end of class ModulatedDeformConvFunction(Function)，but result in a wierd error that:
TypeError: symbolic() takes 10 positional arguments but 11 were given (occurred when translating ModulatedDeformConvFunction)

> @shijianjian the symbolic sample is a diffierent version of DCN. For mmdet version, it should be like
> 
> ```
>     @staticmethod
>     def symbolic(
>             g, input, offset, weight, stride, padding, dilation, groups, deformable_groups,im2col_step
>     ):
>         return g.op(
>             "DCNv2_mmdet",
>             input,
>             offset,
>             weight,
>             stride_i=stride,
>             padding_i=padding,
>             dilation_i=dilation,
>             groups_i=groups,
>             deformable_groups_i=deformable_groups,
>             im2col_step_i=im2col_step
>         )
> ```
> 
> The symbolic can help u export an onnx model, but it can be successfully run. You still need an plugin for DCNv2 in tensorRT like [dcnv2_trt](https://github.com/eweill-nv/dcnv2_trt). Currently,I don`t run DCNv2 well on tensorRT 7.
